server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/markethub
    username: markethub
    password: markethub123

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    url: jdbc:postgresql://localhost:5432/markethub
    user: markethub
    password: markethub123

jwt:
  secret: qgC17PX0z1Cu2ZZSEnoUcYC7MqZd959WwIQEYsKrKrw=
  expiration: 900000

